import { Inter } from "next/font/google";
import "./globals.css";
import Homepage from "@/app/page";
import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Hossam Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" h-screen bg-gradient-to-b from-blue-100 to-red-100 ">
          <div className="h-24">
            <Navbar />
          </div>
          <div className="h-[calc(100vh-6rem)]">{children}</div>
        </div>
      </body>
    </html>
  );
}
